name:                pwned
version:             0.1.0.0
github:              "alexkalderimis/pwned"
license:             BSD3
author:              "Alex Kalderimis"
maintainer:          "alex.kalderimis@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexkalderimis/pwned#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  pwned-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pwned
    - SHA
    - req
    - bytestring
    - data-default
    - text

tests:
  pwned-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pwned
